### ISSUE TITLE
too long engine names

### ISSUE THREAD

**Issue by nescitus** [nescitus/rodent-iv#1]
Reported by xr_a_y on http://talkchess.com/forum3/viewtopic.php?f=2&t=73132&start=30

Android compiles get names like this:

Rodent IV 022 32-bit/CLANG 9.0.8(https://android.googlesource.com/toolchain/llvm-project 207d7abc1a2abf3ef8d4301736d6a7ebc224a290)

Possible solutions: 
1) remove compiler name from the string, possibly expose it by another command
2) erase bracket and/or links from compiler name (more difficult)

**Comment by bcm314** [comment]
Resolved: use __clang_major__ . __clang_minor__ . __clang_patchlevel instead __clang_version__
