### ISSUE TITLE
Makefile missing

### ISSUE THREAD

**Issue by rwbc** [nescitus/rodent-iv#17]
Could you please add a makefile or compiling instructions for users w/o Visualstudio and MS stuff?
I will try how far I come with Rodent III's makefile until then. Thanks!

**Comment by bcm314** [comment]
There's nothing special to say, simply throw all cpp-files into your compiler.
So even shortest variant should work (at least on windows and linux): g++ *.cpp

The only important thing: by default the result will be multithreading, which maybe can make problems (for example mingw don't support it at all).
Add -DNO_THREADS to compile without it.

A few additional polish and maybe you can use:
g++ sources/src/*.cpp -O3 -DNO_THREADS -Wall -Wno-unknown-pragmas -Wno-stringop-truncation -o rodent-iv-cygwin.exe

**Comment by ScallyBag** [comment]
Here’s what I use to compile Rodent IV:




Cheers,

Al

**Comment by rwbc** [comment]
> 
> 
> There's nothing special to say, simply throw all cpp-files into your compiler.
> So even shortest variant should work (at least on windows and linux): g++ *.cpp
> 
> The only important thing: by default the result will be multithreading, which maybe can make problems (for example mingw don't support it at all).
> Add -DNO_THREADS to compile without it.
> 
> A few additional polish and maybe you can use:
> g++ sources/src/*.cpp -O3 -DNO_THREADS -Wall -Wno-unknown-pragmas -Wno-stringop-truncation -o rodent-iv-cygwin.exe

Sorry for the late reply, I forgot about this issue completely.

I had zero problems with extrapolating from a Rodent III makefile.
Thanks anyway for the compiling line above!
