### ISSUE TITLE
Should we remove internal opening book?

### ISSUE THREAD

**Issue by nescitus** [nescitus/rodent-iv#9]
Rodent already can use two .bin books (main one and a guide one). Removing internal book would decrease code base and regain some freedom in fiddling with hash keys (perhaps adding Polyglot keys directly to the engine).

**Comment by bcm314** [comment]
I didn't recognized there are internal opening book before.  ;-)

But how should it work?
I can't figure out.
For example, running "rodent-iv-plain.exe" (from FinalRodent.7z), only have dll's in same directory, no books, no personalities.

Than sending:
`uci`
`isready`
`ucinewgame`
`position startpos`
`go`

No book-move ...

**Comment by nescitus** [comment]
it was not the whole book, but remaining file for its initialization
